export const EMPLOYEES_REQUEST = 'EMPLOYEES_REQUEST';
export const EMPLOYEES_GET_SUCCESS = 'EMPLOYEES_GET_SUCCESS';
export const EMPLOYEES_REMOVE_SUCCESS = 'EMPLOYEES_REMOVE_SUCCESS';
export const EMPLOYEES_FAIL = 'EMPLOYEES_FAIL';

export const DEPARTMENTS_REQUEST = 'DEPARTMENTS_REQUEST';
export const DEPARTMENTS_GET_SUCCESS = 'DEPARTMENTS_GET_SUCCESS';
export const DEPARTMENTS_REMOVE_SUCCESS = 'DEPARTMENTS_REMOVE_SUCCESS';
export const DEPARTMENTS_FAIL = 'DEPARTMENTS_FAIL';

export const TOAST_SHOW = 'TOAST_SHOW';
export const TOAST_CLOSE = 'TOAST_CLOSE';